name: get_paginate_firestore
description: A flutter package to simplify pagination with firestore data using GetX state management.
version: 1.0.0
homepage: https://github.com/djade/paginate_firestore
issue_tracker: https://github.com/djade/paginate_firestore/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.5.4
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
