name: get_paginate_firestore
description: A flutter package to simplify pagination with firestore data using GetX state management.
version: 1.0.0
homepage: https://github.com/djade/paginate_firestore
issue_tracker: https://github.com/djade/paginate_firestore/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  cloud_firestore: ^2.2.2
  provider: ^5.0.0
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1
